name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Gerar Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          filename: github-metrics.svg
          
          template: classic
          
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # 1. Linguagens mais usadas
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          
          # 2. Hábitos de código
          plugin_habits: yes
          plugin_habits_from: 200 # Últimos X commits
          plugin_habits_days: 60
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          # 4. Linhas de código escritas
          plugin_lines: yes
